#! /usr/bin/env perl
# Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

use integer;
use strict;
use warnings;

# --- ВРЕМЕННОЕ РЕШЕНИЕ: задаём год вручную ---
my $YEAR = 2025;

# Generate the DER encoding for the given OID.
sub der_it {
    my ($v) = @_;
    my @a = split(/\s+/, $v);
    die "OID must have at least 2 arcs" unless @a >= 2;
    my $ret = pack("C*", $a[0] * 40 + $a[1]);
    shift @a;
    shift @a;

    foreach (@a) {
        my @r = ();
        my $x = $_;
        while ($x >= 128) {
            push @r, ($x & 0x7f) | 0x80;
            $x >>= 7;
        }
        push @r, $x;
        $ret .= pack("C*", reverse(@r));
    }
    return $ret;
}

# Read input, parse all #define's
my %ln;
my %sn;
my %dupln;
my %dupsn;
my %nid;   # nid{NID_value} = name
my %obj;   # obj{name} = "OBJ_name"
my %objd;  # objd{"OBJ_name"} = "value"

open(my $in, "<", $ARGV[0]) || die "Can't open input file $ARGV[0]: $!";
while (<$in>) {
    next unless /^\#define\s+(\S+)\s+(.*)$/;
    my $macro = $1;
    my $value = $2;
    $value =~ s/^\"//;
    $value =~ s/\"$//;

    if ($macro =~ /^SN_(.*)$/) {
        my $name = $1;
        if (exists $dupsn{$value}) {
            warn "WARNING: Duplicate short name \"$value\"\n";
        }
        $dupsn{$value} = 1;
        $sn{$name} = $value;
    }
    elsif ($macro =~ /^LN_(.*)$/) {
        my $name = $1;
        if (exists $dupln{$value}) {
            warn "WARNING: Duplicate long name \"$value\"\n";
        }
        $dupln{$value} = 1;
        $ln{$name} = $value;
    }
    elsif ($macro =~ /^NID_(.*)$/) {
        my $name = $1;
        $nid{$value} = $name;  # $value = NID number (e.g. "1501")
    }
    elsif ($macro =~ /^OBJ_(.*)$/) {
        my $name = $1;
        $obj{$name} = $macro;
        $objd{$macro} = $value;
    }
}
close $in;

# Expand OBJ_xxx recursively
my $changed;
do {
    $changed = 0;
    for my $k (keys %objd) {
        if ($objd{$k} =~ s/(OBJ_[^,\s]+),/$objd{$1},/) {
            $changed = 1;
        }
    }
} while ($changed);

# Find max NID to size arrays
my @nid_nums = sort { $a <=> $b } grep { $_ =~ /^\d+$/ } keys %nid;
my $max_nid = @nid_nums ? $nid_nums[-1] : 0;
my $n = $max_nid + 1;

my @lvalues = ();
my $lvalues_total = 0;

my @out;
my %obj_der;
my %obj_len;

for my $i (0 .. $n - 1) {
    if (!exists $nid{$i}) {
        push @out, "    { NULL, NULL, NID_undef },\n";
        next;
    }

    my $name = $nid{$i};
    my $sn_val = exists $sn{$name} ? $sn{$name} : "NULL";
    my $ln_val = exists $ln{$name} ? $ln{$name} : "NULL";

    if ($sn_val eq "NULL") { $sn_val = $ln_val; }
    if ($ln_val eq "NULL") { $ln_val = $sn_val; }

    my $line = "    {\"$sn_val\", \"$ln_val\", NID_$name";
    if (exists $obj{$name}) {
        my $obj_macro = $obj{$name};
        my $oid_str = $objd{$obj_macro};
        if ($oid_str =~ /,/) {
            # Expand OID string: "OBJ_bign,2L,1L" → "1 2 112 ... 2 1"
            $oid_str =~ s/L//g;
            $oid_str =~ s/,/ /g;
            my $der = der_it($oid_str);
            my @bytes = unpack("C*", $der);
            my $hex = join(", ", map { sprintf("0x%02X", $_) } @bytes);
            my $len = @bytes;

            $obj_der{$obj_macro} = $hex;
            $obj_len{$obj_macro} = $len;

            push @lvalues, sprintf("    %-45s /* [%5d] %s */\n",
                $hex . ",", $lvalues_total, $obj_macro);
            $line .= ", $len, so + $lvalues_total";
            $lvalues_total += $len;
        }
    }
    $line .= "},\n";
    push @out, $line;
}

# Output
print <<"EOF";
/*
 * WARNING: do not edit!
 * Generated by crypto/objects/obj_dat.pl
 *
 * Copyright 1995-$YEAR The OpenSSL Project Authors. All Rights Reserved.
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

EOF

print "/* Serialized OID's */\n";
printf "static const unsigned char so[%d] = {\n", $lvalues_total;
print @lvalues;
print "};\n\n";

printf "#define NUM_NID %d\n", $n;
print "static const ASN1_OBJECT nid_objs[NUM_NID] = {\n";
print @out;
print "};\n\n";

# SN table
my @sn_indices = grep { exists $sn{$nid{$_}} } 0 .. $n - 1;
printf "#define NUM_SN %d\n", scalar(@sn_indices);
print "static const unsigned int sn_objs[NUM_SN] = {\n";
for my $i (sort { $sn{$nid{$a}} cmp $sn{$nid{$b}} } @sn_indices) {
    printf "    %4d,    /* \"%s\" */\n", $i, $sn{$nid{$i}};
}
print "};\n\n";

# LN table
my @ln_indices = grep { exists $ln{$nid{$_}} } 0 .. $n - 1;
printf "#define NUM_LN %d\n", scalar(@ln_indices);
print "static const unsigned int ln_objs[NUM_LN] = {\n";
for my $i (sort { $ln{$nid{$a}} cmp $ln{$nid{$b}} } @ln_indices) {
    printf "    %4d,    /* \"%s\" */\n", $i, $ln{$nid{$i}};
}
print "};\n\n";

# OBJ table
my @obj_indices = grep { exists $obj{$nid{$_}} } 0 .. $n - 1;
printf "#define NUM_OBJ %d\n", scalar(@obj_indices);
print "static const unsigned int obj_objs[NUM_OBJ] = {\n";
for my $i (sort { 
    my $a_len = $obj_len{$obj{$nid{$a}}};
    my $b_len = $obj_len{$obj{$nid{$b}}};
    ($a_len <=> $b_len) || ($obj_der{$obj{$nid{$a}}} cmp $obj_der{$obj{$nid{$b}}})
} @obj_indices) {
    my $macro = $obj{$nid{$i}};
    my $oid_raw = $objd{$macro};
    $oid_raw =~ s/L//g;
    $oid_raw =~ s/,/ /g;
    printf "    %4d,    /* %-32s %s */\n", $i, $macro, $oid_raw;
}
print "};\n";