/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_BIGNERR_H
# define HEADER_BIGNERR_H

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_BIGN
#include <openssl/err.h>
#  ifdef  __cplusplus
extern "C"
#  endif
int ERR_load_BIGN_strings(void);

/*
 * BIGN function codes.
 */
#  define BIGN_F_I2D_BIGNPARAMETERS                        121
#  define BIGN_F_D2I_BIGNPARAMETERS                        122
#  define BIGN_F_I2O_BIGNPUBLICKEY                         123
#  define BIGN_F_O2I_BIGNPUBLICKEY                         124
#  define BIGN_F_I2D_BIGNPRIVATEKEY                        125
#  define BIGN_F_D2I_BIGNPRIVATEKEY                        126

#  define BIGN_F_PARAM2TYPE                                131
#  define BIGN_F_PUB_ENCODE                                132
#  define BIGN_F_TYPE2PARAM                                133
#  define BIGN_F_PUB_DECODE                                134
#  define BIGN_F_PRIV_ENCODE                               135
#  define BIGN_F_PRIV_DECODE                               136
#  define BIGN_F_PARAM_DECODE                              137
#  define BIGN_F_DO_BIGN_PRINT                             138

#  define BIGN_F_PKEY_BIGN_INIT                            141
#  define BIGN_F_PKEY_BIGN_PARAMGEN                        142
#  define BIGN_F_PKEY_BIGN_KEYGEN                          143
#  define BIGN_F_PKEY_BIGN_SIGN                            144
#  define BIGN_F_PKEY_BIGN_DERIVE                          145
#  define BIGN_F_PKEY_BIGN_CTRL                            146
#  define BIGN_F_PKEY_BIGN_CTRL_STR                        147

#  define BIGN_F_BIGN_NEW                                  151
#  define BIGN_F_BIGN_GENERATE_KEY                         152
#  define BIGN_F_BIGN_GET_PRIVKEY                          153
#  define BIGN_F_BIGN_GET_PUBKEY                           154
#  define BIGN_F_BIGN_SET_PRIVKEY                          155
#  define BIGN_F_BIGN_CHECK_PUBKEY                         156
#  define BIGN_F_BIGN_SET_PUBKEY                           157

#  define BIGN_F_BIGN_GENK                                 161
#  define BIGN_F_BIGN_SIGN                                 162
#  define BIGN_F_BIGN_VERIFY                               163
#  define BIGN_F_CREATE_TOKEN                              164
#  define BIGN_F_DECODE_TOKEN                              165

/*
 * BIGN reason codes.
 */
#  define BIGN_R_MISSING_PARAMETERS                        121
#  define BIGN_R_MISSING_OID                               122
#  define BIGN_R_DECODE_ERROR                              123
#  define BIGN_R_NO_PARAMETERS_SET                         124
#  define BIGN_R_INVALID_DIGEST_LENGTH                     125
#  define BIGN_R_INVALID_PRIVATE_KEY                       126
#  define BIGN_R_INVALID_PUBLIC_KEY                        127
#  define BIGN_R_INVALID_PEER_KEY                          128
#  define BIGN_R_INVALID_CURVE                             129
#  define BIGN_R_INVALID_SIGN_LENGTH                       130
#  define BIGN_R_BIGN_VERIFY_FAIL                          131
#  define BIGN_R_KEYS_NOT_SET                              132

# define ERR_LIB_BIGN            70
# define ERR_R_BIGN_LIB          (ERR_LIB_BIGN | ERR_RFLAG_COMMON)

#  define BIGNerr(f, r) ERR_raise_data(ERR_LIB_BIGN, (r), NULL)

# endif
#endif
